### ISSUE TITLE
Show first notification after loading metadata

### ISSUE THREAD

**Issue by megadr01d** [kode54/Cog#33]
I don't know if this is a OS limitation but is it possible to delay the first notification, when loading an album with Cog in the background, until the metadata is loaded?

First song notification with Cog in the background
![nometadata](https://u.teknik.io/1cxnn.png)

Notification of the same song when switching with system wide shortcut
![metadata](https://u.teknik.io/x5Yuk.png)

**Comment by megadr01d** [comment]
![1](https://u.teknik.io/Id8cu.png)

![2](https://u.teknik.io/W0ZhN.png)

**Comment by kode54** [comment]
This is only happening because metadata is delay loaded. I suppose I could do like foobar2000 and forcibly load all metadata up front when all tracks are added. I wouldn't know the first thing about displaying a progress dialog for that, either, so I'll just sit there doing nothing until the data is loaded, then the tracks will appear and start playing.

**Comment by megadr01d** [comment]
Just a thought, what about force loading metadata only on the first track, start playing it, and then add the rest of the tracks and metadata slowly in the background?

Otherwise, waiting for all metadata to be loaded, before starting playback, can take a long time when adding a whole discography to the playlist, and it's better to leave it as it is.

**Comment by kode54** [comment]
Ooh, a very good idea. I’ll get right on that either tonight or tomorrow.

**Comment by megadr01d** [comment]
Seems to be working great so far. Thumbs up and cheers.
